name: DropHeads
version: ${project.version}
main: me.lordburtz.dropheads.DropHeads
api-version: 1.16
authors: [ LordBurtz ]
description: mobs drop Heads on kill
website: https://github.com/LordBurtz
depend: ["Vault"]

commands:
  sell-heads:
    aliases: []
    description: "sell the heads in your hand"

  test:
    aliases: []

  level:
    aliases: []

  reset-xp:
    aliases: []